[package]
name = "good-lls"
version = "0.1.0"
authors = ["Justin Jaffray <justin.jaffray@gmail.com>"]

[dependencies]
lazy_static = "0.1.*"
clap = "~2.19.0"
oauth-client = { git = "https://github.com/justinj/oauth-client-rs" }
cairo = "0.0.4"
rustc-serialize = "0.3"

[profile.release]
debug = true
